# Generated by Django 2.2.5 on 2020-12-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('moblieno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=150)),
                ('diseases', models.CharField(max_length=200)),
                ('packagep', models.CharField(max_length=50)),
                ('packages', models.DateTimeField()),
                ('packagee', models.DateTimeField()),
                ('feesp', models.CharField(max_length=10)),
                ('tranningtype', models.CharField(max_length=20)),
                ('dob', models.DateField()),
            ],
        ),
    ]
