# Generated by Django 2.2.5 on 2021-01-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetails',
            name='age',
            field=models.DurationField(),
        ),
    ]
